services:
  flask:
    build:
      context: ./flask  # Path to the Flask application directory
    ports:
      - "5000:5000"  # Map port 5000 inside the container to port 5000 on the host
    volumes:
      - ./flask:/app  # Mount the Flask app directory
    environment:
      - FLASK_APP=app.py  # Set Flask environment variable
    depends_on:
      - db

  django:
    build:
      context: ./myproject  # Path to the Django application directory
    ports:
      - "8000:8000"  # Map port 8000 inside the container to port 8000 on the host
    volumes:
      - ./myproject:/app  # Mount the Django app directory
    environment:
      - PYTHONUNBUFFERED=1  # Ensure stdout/stderr are not buffered
    depends_on:
      - db

  db:
    image: postgres:13  # Use PostgreSQL as the database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
